apiVersion: v1
kind: Secret
metadata:
  name: economia-secrets
  namespace: economia
type: Opaque
stringData:
  sql-sa-password: "EconomIA_Dev2024!"
  sql-connection-string: "Server=sqlserver-service,1433;Database=EconomIA;User Id=sa;Password=EconomIA_Dev2024!;TrustServerCertificate=True"
  redis-password: ""
  vault-token: "economia-dev-token"
